# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false
# Use custom format
format = """
(bold green)\
$username\
$hostname\
$localip\
$kubernetes\
$directory\
$helm\
$terraform\
$aws\
$shell
[└─>](bold green) $git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$character
"""

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

[helm]
detect_folders = ['helm', 'helm2']

[hostname]
disabled = false
ssh_only = false

[kubernetes]
disabled = false

[kubernetes.context_aliases]
"kind-edge-dev" = "dev"
"" = ""

[localip]
disabled = false
ssh_only = true